### ISSUE TITLE
Missing Facebook's GamingServicesKit binding

### ISSUE THREAD

**Issue by CoderBaron** [dkimitsa/robovm-robopods#22]
Do you plan to add a binding to Facebook's GamingServicesKit?

I have a yaml file from my own collection. I quickly adapted it for your repo:

```yaml
package: org.robovm.pods.facebook.gamingservices
framework: FBSDKGamingServicesKit
include:
    - foundation
    - coregraphics
    - uikit
    - ../../../../ios-core-basics/src/main/bro-gen/facebook-core-basics.yaml
clang_args: ['-x', 'objective-c', '-fobjc-arc', '-Ffacebook/ios-aem/src/main/bro-gen/']
headers:
    - FBSDKGamingServicesKit-Swift.h
    
enums:
    FBSDKChooseContextFilter: {}
    FBSDKGameRequestActionType: {}
    FBSDKGameRequestFilter: {}
    _FBSDKTournamentScoreType: { exclude: true }
    _FBSDKTournamentSortOrder: { exclude: true }

classes:
    FBSDKChooseContextContent:
        methods:
            '+filtersNameForFilters:':
                name: getFiltersName
    FBSDKChooseContextDialog:
        methods:
            '-initWithContent:delegate:':
                name: init
                constructor: false # store delegate
            '-application:openURL:sourceApplication:annotation:':
                name: openURL
            '-canOpenURL:forApplication:sourceApplication:annotation:':
                name: canOpenURL
            '-applicationDidBecomeActive:':
                name: didBecomeActive
            '-validateAndReturnError:':
                name: validate
                throws: NSErrorException
    FBSDKContextDialogPresenter:
        methods:
            '-makeAndShowCreateContextDialogWithContent:delegate:error:':
                name: makeAndShowCreateContextDialog
                throws: NSErrorException
                visibility: private # store delegate
            '-makeAndShowSwitchContextDialogWithContent:delegate:error:':
                name: makeAndShowSwitchContextDialog
                throws: NSErrorException
                visibility: private # store delegate
            '-makeAndShowChooseContextDialogWithContent:delegate:':
                name: makeAndShowChooseContextDialog
                visibility: private # store delegate
            '+showCreateContextDialogWithContent:delegate:':
                exclude: true # deprecated
            '+showSwitchContextDialogWithContent:delegate:':
                exclude: true # deprecated
            '+showChooseContextDialogWithContent:delegate:':
                exclude: true # deprecated
            '+showChooseContextDialogWith:delegate:':
                exclude: true # deprecated
            '+createContextDialogWithContent:delegate:':
                exclude: true # deprecated
            '+switchContextDialogWithContent:delegate:':
                exclude: true # deprecated
    FBSDKContextWebDialog:
        properties:
            currentWebDialog:
                exclude: true
        methods:
            '-webDialog:didCompleteWithResults:':
                name: didComplete
                exclude: true
            '-webDialog:didFailWithError:':
                name: didFail
                exclude: true
            '-webDialogDidCancel:':
                name: didCancel
                exclude: true
            '-createWebDialogFrameWithWidth:height:windowFinder:':
                exclude: true
            '-validateAndReturnError:':
                name: validate
                throws: NSErrorException
    FBSDKCreateContextContent:
        methods:
            '-initDialogContentWithPlayerID:':
                name: init
                exclude: true
    FBSDKCreateContextDialog:
        methods:
            '-initWithContent:windowFinder:delegate:':
                name: init
                constructor: false # store delegate
    FBSDKFriendFinderDialog:
        methods:
            '+launchFriendFinderDialogWithCompletionHandler:':
                name: launchFriendFinderDialog
    FBSDKGameRequestContent:
        properties:
            '(recipients|recipientSuggestions)':
                type: List<String>
                marshaler: NSArray.AsStringListMarshaler
        methods:
            '-isEqualToGameRequestContent:':
                name: isEqual
            '-validateWithOptions:error:':
                name: validate
                throws: NSErrorException
            '-initWithCoder:':
                name: init
            '-encodeWithCoder:':
                name: encode
    FBSDKGameRequestDialog:
        properties:
            isFrictionlessRequestsEnabled:
                setter: setFrictionlessRequestsEnabled
        methods:
            '-initWithContent:delegate:':
                name: init
                constructor: false # store delegate
            '-validateWithError:':
                name: validate
                throws: NSErrorException
            '+dialogWithContent:delegate:':
                exclude: true
            '+showWithContent:delegate:':
                name: show0
                visibility: private # store delegate
            '-webDialog:didCompleteWithResults:':
                name: didComplete
                exclude: true
            '-webDialog:didFailWithError:':
                name: didFail
                exclude: true
            '-webDialogDidCancel:':
                name: didCancel
                exclude: true
            '-application:openURL:sourceApplication:annotation:':
                name: openURL
                exclude: true
            '-canOpenURL:forApplication:sourceApplication:annotation:':
                name: canOpenURL
                exclude: true
            '-applicationDidBecomeActive:':
                name: didBecomeActive
                exclude: true
    FBSDKGameRequestURLProvider:
        methods:
            '+createDeepLinkURLWithQueryDictionary:':
                name: createDeepLinkURL
            '+filtersNameForFilters:':
                name: getFiltersName
            '+actionTypeNameForActionType:':
                name: getActionTypeName
    FBSDKGamingContext:
        methods:
            '-initWithIdentifier:size:':
                name: init
            '+currentContext':
                property: true
    FBSDKGamingGroupIntegration:
        methods:
            '+openGroupPageWithCompletionHandler:':
                name: openGroupPage
    FBSDKGamingImageUploader:
        methods:
            '+uploadImageWithConfiguration:andResultCompletion:':
                name: uploadImage
            '+uploadImageWithConfiguration:completion:andProgressHandler:':
                name: uploadImage
            '-requestConnection:didSendBodyData:totalBytesWritten:totalBytesExpectedToWrite:':
                name: requestConnection
    FBSDKGamingImageUploaderConfiguration:
        methods:
            '-initWithImage:caption:shouldLaunchMediaDialog:':
                name: init
    FBSDKGamingPayload:
        methods:
            '-initWithURL:':
                name: init
    FBSDKGamingPayloadObserver:
        methods:
            '-initWithDelegate:':
                name: init
                constructor: false # store delegate
            '-application:openURL:sourceApplication:annotation:':
                name: openURL
    FBSDKGamingVideoUploader:
        methods:
            '+uploadVideoWithConfiguration:andResultCompletion:':
                name: uploadVideo
            '+uploadVideoWithConfiguration:completion:andProgressHandler:':
                name: uploadVideo
    FBSDKGamingVideoUploaderConfiguration:
        methods:
            '-initWithVideoURL:caption:':
                name: init
    FBSDKSwitchContextContent:
        methods:
            '-initDialogContentWithContextID:':
                name: init
    FBSDKSwitchContextDialog:
        methods:
            '-initWithContent:windowFinder:delegate:':
                name: init
                constructor: false # store delegate
            '+dialogWithContent:windowFinder:delegate:':
                exclude: true
    ShareTournamentDialog:
        name: FBSDKShareTournamentDialog
        methods:
            '-application:openURL:sourceApplication:annotation:':
                name: openURL
                exclude: true
            '-canOpenURL:forApplication:sourceApplication:annotation:':
                name: canOpenURL
                exclude: true
            '-applicationDidBecomeActive:':
                name: didBecomeActive
                exclude: true
    _FBSDKShareTournamentDialog:
        exclude: true
    _FBSDKTournament:
        exclude: true
    _FBSDKTournamentConfig:
        exclude: true
    _FBSDKTournamentFetcher:
        exclude: true
    _FBSDKTournamentUpdater:
        exclude: true

protocols:
    FBSDKContextDialogDelegate:
        methods:
            '-contextDialogDidComplete:':
                name: didComplete
            '-contextDialog:didFailWithError:':
                name: didFail
            '-contextDialogDidCancel:':
                name: didCancel
    FBSDKDialog:
        skip_adapter: true
        methods:
            '-validateAndReturnError:':
                name: validate
                throws: NSErrorException
    FBSDKGameRequestDialogDelegate:
        methods:
            '-gameRequestDialog:didCompleteWithResults:':
                name: didComplete
            '-gameRequestDialog:didFailWithError:':
                name: didFail
            '-gameRequestDialogDidCancel:':
                name: didCancel
    FBSDKGamingPayloadDelegate:
        methods:
            '-parsedGameRequestURLContaining:gameRequestID:':
                name: parsedGameRequestURL
            '-parsedTournamentURLContaining:tournamentID:':
                name: parsedTournamentURL
    FBSDKShowable:
        skip_adapter: true
    FBSDKValidatable:
        skip_adapter: true
        methods:
            '-validateAndReturnError:':
                name: validate
                throws: NSErrorException
    _FBSDKShareTournamentDialogDelegate:
        exclude: true

functions:
    # Make sure we don't miss any functions if new ones are introduced in a later version
    (.*):
        class: __FixMe
        name: 'Function__#{g[0]}'

values:
    # Make sure we don't miss any values if new ones are introduced in a later version
    (.*):
        class: __FixMe
        name: 'Value__#{g[0]}'

constants:
    # Make sure we don't miss any constants if new ones are introduced in a later version
    (.*):
        class: __Fixme
        name: 'Constant__#{g[0]}'

```

One thing to note: There are many methods (inits and others) that require passing a delegate object. These objects need to have a strong reference otherwise they will be gc'ed immediately.
By default delegate properties get marked as strong ref properties but I'm unaware of a way to do this with delegate method parameters. So all methods I marked with `# store delegate` would need to be manually duplicated with an additional call to `addStrongRef(delegate)`

The same applies to this method here: https://github.com/dkimitsa/robovm-robopods/blob/alt/facebook/ios-core/src/main/java/org/robovm/pods/facebook/core/FBSDKGraphErrorRecoveryProcessor.java#L66
and probably some other places too. 
Would it be possible in the future to add a `@StrongRef` annotation to robovm which automatically handles this?
